pipeline:
  build:
    image: python:3.5.1-alpine
    commands:
      - pip install --no-cache-dir --upgrade pip setuptools wheel flake8
      - flake8 run_devpi.py
      - pip wheel -r requirements.txt --wheel-dir=wheeldir --find-links=wheeldir
      - pip install --use-wheel --no-index --find-links=wheeldir -r requirements.txt
      - python test.py

  docker:
    repo: dronepython/plugin-devpi
    when:
      branch: master
      event: push

services:
  devpi:
    image: muccg/devpi:latest
